
CREATE TABLE IF NOT EXISTS users(
  id SERIAL PRIMARY KEY,
  firstName VARCHAR(100) NOT NULL,
  lastName VARCHAR(100),
  password VARCHAR NOT NULL
);
CREATE TABLE IF NOT EXISTS orders(
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
  status VARCHAR(50) DEFAULT 'active'
);