CREATE TABLE order_products(
  id SERIAL PRIMARY KEY,
  product_id INTEGER REFERENCES products(id) ON DELETE CASCADE ON UPDATE CASCADE,
  order_id INTEGER REFERENCES orders(id)  ON DELETE CASCADE ON UPDATE CASCADE,
  quantity INTEGER DEFAULT 1
)