
CREATE TABLE IF NOT EXISTS users(
  id SERIAL PRIMARY KEY,
  firstName VARCHAR(100) NOT NULL,
  lastName VARCHAR(100),
  password VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS orders(
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
  status VARCHAR(50) DEFAULT 'active'
);

CREATE TABLE IF NOT EXISTS products(
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  price MONEY NOT NULL,
  category VARCHAR(100)
);
CREATE TABLE IF NOT EXISTS order_products(
  id SERIAL PRIMARY KEY,
  product_id INTEGER REFERENCES products(id) ON DELETE CASCADE ON UPDATE CASCADE,
  order_id INTEGER REFERENCES orders(id)  ON DELETE CASCADE ON UPDATE CASCADE,
  quantity INTEGER DEFAULT 1
)